# Generated by Django 4.1.5 on 2023-02-13 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Category',
            new_name='category',
        ),
    ]
